# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sami Keinänen - Resume
email: skope@iki.fi
description: Resume for Sami Keinänen
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://skope.github.io" # the base hostname & protocol for your site
twitter_username: skouppi
github_username:  skope

# Build settings
markdown: kramdown
host: 0.0.0.0
repository: skope/skope.github.io